name: Terraform Github Actions
on: [push]
jobs:
  Terraform-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
      
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: AKIAZ36CQFU4ZBB2NCH4
          AWS_SECRET_ACCESS_KEY: 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
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: AKIAZ36CQFU4ZBB2NCH4
          AWS_SECRET_ACCESS_KEY: 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
        run: terraform apply -auto-approve
        continue-on-error: true
        id: apply     

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "üçè This job's status is ${{ job.status }}."