name: Terraform Github Actions
on: [push]
jobs:
  Terraform-Actions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: AWS Credentials Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ AWS_REGION }}
        run: |
          mkdir -p $HOME/.aws
          touch $HOME/.aws/credentials

          echo "[default]
          aws_access_key_id = ${{ AWS_ACCESS_KEY_ID }}
          aws_secret_access_key = ${{ AWS_SECRET_ACCESS_KEY }}
          " > $HOME/.aws/credentials 

          echo "$(< $HOME/.aws/credentials )" 

          set AWS_ACCESS_KEY_ID= ${{ AWS_ACCESS_KEY_ID }}
          set AWS_SECRET_ACCESS_KEY= ${{ AWS_SECRET_ACCESS_KEY }}
          set AWS_REGION= ${{ AWS_REGION }}

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform apply -auto-approve
        continue-on-error: true
        id: apply     

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - run: echo "ðŸ This job's status is ${{ job.status }}."